export const CITY_ACQUIRED = "CITY_ACQUIRED";
export const ITINERARY_ACQUIRED = "ITINERARY_ACQUIRED";
export const ACTIVITY_ACQUIRED = "ACTIVITY_ACQUIRED";
export const COMMENT_ACQUIRED = "COMMENT_ACQUIRED";
export const COMMENT_POSTED = "COMMENT_POSTED";